
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache = true
cache_path = "cache"
solc_version = "0.8.20"

[fmt]
line_length = 120

[fuzz]
runs = 500

[invariant]
runs = 500
depth = 50
